server:
  port: 8080

logging:
  level:
    com.kenny.demo.transactionaldemo: DEBUG
    org.hibernate.type.descriptor.sql : DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create-drop